### ISSUE TITLE
NumberFormatException caused by Invalid Inputs

### ISSUE THREAD

**Issue by slumdroid** [rengolin/cardgamescores#10]
App crashes with the following stack traces when "Maximum Score" is the character "-" or is a big number.

E/AndroidRuntime( 2236): FATAL EXCEPTION: main
E/AndroidRuntime( 2236): java.lang.IllegalStateException: Could not execute method of the activity
E/AndroidRuntime( 2236): 	at android.view.View$1.onClick(View.java:3591)
E/AndroidRuntime( 2236): 	at android.view.View.performClick(View.java:4084)
E/AndroidRuntime( 2236): 	at android.view.View$PerformClick.run(View.java:16966)
E/AndroidRuntime( 2236): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 2236): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2236): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2236): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 2236): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2236): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2236): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 2236): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2236): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2236): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2236): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2236): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2236): 	at android.view.View$1.onClick(View.java:3586)
E/AndroidRuntime( 2236): 	... 11 more
E/AndroidRuntime( 2236): Caused by: java.lang.NumberFormatException: Invalid int: "12345678901234567890"
E/AndroidRuntime( 2236): 	at java.lang.Integer.invalidInt(Integer.java:138)
E/AndroidRuntime( 2236): 	at java.lang.Integer.parse(Integer.java:378)
E/AndroidRuntime( 2236): 	at java.lang.Integer.parseInt(Integer.java:366)
E/AndroidRuntime( 2236): 	at java.lang.Integer.parseInt(Integer.java:332)
E/AndroidRuntime( 2236): 	at java.lang.Integer.valueOf(Integer.java:490)
E/AndroidRuntime( 2236): 	at org.systemcall.scores.AddPlayersActivity.startGame(AddPlayersActivity.java:60)
E/AndroidRuntime( 2236): 	... 14 more

E/AndroidRuntime( 2215): FATAL EXCEPTION: main
E/AndroidRuntime( 2215): java.lang.IllegalStateException: Could not execute method of the activity
E/AndroidRuntime( 2215): 	at android.view.View$1.onClick(View.java:3591)
E/AndroidRuntime( 2215): 	at android.view.View.performClick(View.java:4084)
E/AndroidRuntime( 2215): 	at android.view.View$PerformClick.run(View.java:16966)
E/AndroidRuntime( 2215): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 2215): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2215): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2215): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 2215): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2215): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2215): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 2215): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2215): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2215): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2215): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2215): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2215): 	at android.view.View$1.onClick(View.java:3586)
E/AndroidRuntime( 2215): 	... 11 more
E/AndroidRuntime( 2215): Caused by: java.lang.NumberFormatException: Invalid int: "-"
E/AndroidRuntime( 2215): 	at java.lang.Integer.invalidInt(Integer.java:138)
E/AndroidRuntime( 2215): 	at java.lang.Integer.parseInt(Integer.java:363)
E/AndroidRuntime( 2215): 	at java.lang.Integer.parseInt(Integer.java:332)
E/AndroidRuntime( 2215): 	at java.lang.Integer.valueOf(Integer.java:490)
E/AndroidRuntime( 2215): 	at org.systemcall.scores.AddPlayersActivity.startGame(AddPlayersActivity.java:60)
E/AndroidRuntime( 2215): 	... 14 more

**Comment by slumdroid** [comment]
App crashes with empty string, too...
("play forever?" is not checked)

**Comment by rengolin** [comment]
Hi Gennaro, Thanks for the report. I tried adding some silly validation (catch & ignore), but obviously that wasn't enough. To properly fix this issue I have to:

1. Validate all possible shenanigans people can write in there, reset to empty string
2. If the string is empty on start, assume "play forever"

I'll add this bug to the next release, but since it's not such a critical problem, and I'll be away for some time, it might take a while.
